### ISSUE TITLE
Text in the terminal seems to blur when it gets too long.

### ISSUE THREAD

**Issue by Froggo8311** [Froggo8311/BrowserLinux#6]

**Comment by Froggo8311** [comment]
This probably isn't a big deal at the moment, closing for now.

**Comment by Froggo8311** [comment]
nevermind, its a bit too annoying :/

**Comment by Froggo8311** [comment]
It seems this is only a Google Chrome issue. Other browsers, it seems, do not encounter this issue.

**Comment by NovaAndrom3da** [comment]
See dev branch for latest changes.
