### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by ThatOneCalculator** [Froggo8311/BrowserLinux#7]
Both in Firefox and Chromium (Vivaldi)

![image](https://user-images.githubusercontent.com/44733677/159140425-af42f739-a81c-4ada-8bd6-4f1de553fbaf.png)

**Comment by NLTD2010** [comment]
![image](https://user-images.githubusercontent.com/77970269/160115517-b15a4159-4d42-4b7c-9d03-741f368d0ad2.png)
error here

**Comment by Froggo8311** [comment]
The vercel is fixed. It seems I had set the build output to the wrong folder, so it was looking in the wrong place.
